name: Lint workflows

on:
  push:
    branches:
      - "**"
    paths:
      - ".github/workflows/*.yml"
  pull_request:
    paths:
      - ".github/workflows/*.yml"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Run actionlint
        uses: reviewdog/action-actionlint@5eaffa19a1991ecc52b11eddcdd57760d1ac7e3d # v1.72.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@5f14fd08f7cf1cb1609c1e344975f152c7ee938d # v0.5.6
        with:
          inputs: ".github/workflows/"
          token: ${{ secrets.GITHUB_TOKEN }}
