name: Lint workflows

on:
  push:
    branches:
      - "**"
    paths:
      - ".github/workflows/*.yml"
  pull_request:
    paths:
      - ".github/workflows/*.yml"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Run actionlint
        uses: reviewdog/action-actionlint@50b75b9513baa71e6a1899a1ebaa9ac9851cf16c # v1.66.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@e639db99335bc9038abc0e066dfcd72e23d26fb4 # v0.3.0
        with:
          inputs: ".github/workflows/"
          token: ${{ secrets.GITHUB_TOKEN }}
