name: Build & release obsidian plugin

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "*" # Push events to matching any tag format, i.e. 1.0, 20.15.10

env:
  PLUGIN_NAME: japanese-novel-ruby # Change this to the name of your plugin-id folder

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      attestations: write

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Use Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: "20.x" # You might need to adjust this value to your own version
      - name: Build
        id: build
        run: |
          npm install
          npm run build
      - name: Package
        run: |
          tag="${GITHUB_REF#refs/tags/}"
          mkdir "$PLUGIN_NAME"
          cp main.js styles.css manifest.json "$PLUGIN_NAME"
          zip -r "$PLUGIN_NAME-$tag.zip" "$PLUGIN_NAME"
          echo "TAG_NAME=$tag" >> $GITHUB_ENV
      - name: Attest Build Provenance
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: |
            main.js
            styles.css
            manifest.json
            ${{ env.PLUGIN_NAME }}-${{ env.TAG_NAME }}.zip
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ env.TAG_NAME }}
        run: |
          gh release create "$TAG_NAME" \
            --title="$TAG_NAME" \
            --draft \
            main.js styles.css manifest.json "$PLUGIN_NAME-$TAG_NAME.zip"